local S = {
  state_changed_at = 0,
  rp_compact = false,
  lp_compact = false,
  seed_quip = nil,
  seed_quip_src = nil,
  panel_font = nil,
  panel_font_small = nil,
  wrap_cache = {},
  wrap_cache_keys = {},
  ov = {
    trunc = {}, trunc_keys = {},
    panel = {}, shop = {}, pack = {}, built_at = 0, built_sn = nil,
    money_disp = nil, money_from = nil, money_target = nil, money_start_at = 0,
    act_text = nil, act_at = 0,
    sl_text = nil, sl_at = 0,
  },
  menu_enter_t = nil,
  auto_login_fired = false,
  neuro_logo = nil,
  neuro_logo_attempts = 0,
  quad_cache = {},
  panel_emote_cache = {},
  panel_emote_attempts = {},
  neuro_card_draw_hooked = false,
  card_glow_fade = setmetatable({}, { __mode = "k" }),
  panel_y_current = 6,
  panel_y_last_time = 0,
  panel_y_from = 6,
  panel_y_target = nil,
  panel_y_at = 0,
  right_panel_slide_frac = 0,
  rp_slide_from = 0,
  rp_slide_target = 0,
  rp_slide_at = 0,
  left_panel_slide_frac = 0,
  lp_slide_from = 0,
  lp_slide_target = 0,
  lp_slide_at = 0,
  shop_appear_t = 0,
  shop_last_visible = false,
  panel_h_current = 0,
  known_joker_refs = nil,
  known_cons_refs = nil,
  joker_showcase = nil,
  joker_showcase_q = {},
  pack_gained_q = {},
  desc_slot = 0,
  desc_epoch = false,         -- false = unsynced
  desc_cache = {},
  desc_cache_n = -1,
  cons_slot = 0,
  cons_epoch = false,
  cons_cache = {},
  cons_cache_n = -1,
  buy_showcase = nil,
  pack_prev_cards = {},
  pack_picked = {},
  pack_appear_t = 0,
  pack_last_sn = nil,
  pack_card_indices = {},
  pack_initial_count = 0,
  known_voucher_keys = nil,   -- nil until first observation (skip-first)
  voucher_order = {},
  voucher_anim = {},
  voucher_wrap = {},
  voucher_fx = {},            -- P_CENTERS static so cache survives runs; never invalidated
  voucher_seg = {},           -- key -> stride-3 {str,is_gold,px_w} segments; false = plain fallback
  voucher_seg_fit = {},
  voucher_tier2 = {},         -- false, never nil: negative-cached once probed
  voucher_count_pulse_at = 0,
  voucher_rot_idx = 1,
  voucher_rot_prev = 1,
  voucher_rot_epoch = false,  -- false = unsynced
  voucher_rot_hold_until = 0,
  voucher_rot_slide_at = 0,
  voucher_game_ref = nil,     -- G.GAME identity; changes on new run / save load
  drawer_slide_frac = 0,
  drawer_slide_from = 0,
  drawer_slide_target = 0,
  drawer_slide_at = 0,
  drawer_ext_from = 0,
  drawer_ext_target = 0,
  drawer_ext_at = 0,
  drawer_h_current = 0,
  drawer_reserve = 0,
}
return S
