
local REAL, TOTAL, WALL = "REAL", "TOTAL", "WALL"
-- Clock semantics: SPEEDFACTOR is NOT G.SETTINGS.GAMESPEED (it reads 1 off the run stage and
-- during screen wipes); dt_smooth is smoothed game time, never wall time; G.fbf is a game-clock
-- quantity -- each gate below states which of these clocks its defer window is measured on.

local gates = {
  { id = "engine_gate_failsafe", clock = TOTAL, file = "core/transition_guard.lua",
    knobs = { "NEURO_ENGINE_GATE_FAILSAFE" }, wired = true,
    why = "releases an E_MANAGER queue or CONTROLLER lock that never drained, and draining is animation" },
  { id = "controller_lock_leak", clock = TOTAL, file = "core/transition_guard.lua", wired = true,
    why = "a CONTROLLER lock is cleared by the game event that took it, so its age is game time" },
  { id = "action_settle_latch", clock = TOTAL, file = "core/transition_guard.lua", wired = true,
    why = "holds an action off while the previous one is still resolving on screen" },
  { id = "router_pack_exit_defer", clock = TOTAL, file = "force/force_router.lua",
    knobs = { "NEURO_ROUTER_DEFER_FAILSAFE" }, wired = true,
    why = "waits for the pack to finish closing before a force may name pack actions again" },
  { id = "router_guard_defer", clock = TOTAL, file = "force/force_router.lua",
    knobs = { "NEURO_ROUTER_DEFER_FAILSAFE" }, wired = true,
    why = "waits out the transition guard, which is itself on TOTAL" },
  { id = "staging_failsafe", clock = TOTAL, file = "core/staging.lua",
    knobs = { "NEURO_STAGING_FAILSAFE" }, wired = true,
    why = "bounds a staged action whose hover and commit phases are paced against the game" },
  { id = "staging_hover", clock = TOTAL, file = "core/staging.lua",
    knobs = { "NEURO_HOVER_PER_CARD", "NEURO_HOVER_SHOP", "NEURO_HOVER_USE", "NEURO_HOVER_DEFAULT" },
    wired = true,
    why = "the card lift it paces is a game animation; the engine must see the hover before the click" },
  { id = "staging_hold", clock = TOTAL, file = "core/staging.lua",
    knobs = { "NEURO_HOLD_ALL_SELECTED" }, wired = true,
    why = "holds the fully selected hand on screen for as long as the game draws it" },
  { id = "staging_commit", clock = TOTAL, file = "core/staging.lua",
    knobs = { "NEURO_SHOP_BUY_DELAY", "NEURO_PACK_PICK_DELAY" }, wired = true,
    why = "mirrors the commit event handlers/*.lua schedule on the TOTAL timer, waiting on the same animation" },
  { id = "staging_engine_floor", clock = REAL, file = "core/staging.lua", wired = true,
    why = "the card's spring motion runs on real_dt (dump game.lua:2760-2765) and never speeds up" },
  { id = "glow_window", clock = REAL, file = "core/staging.lua", wired = true,
    why = "hud/cards.lua ramps the AI glow against REAL, next to that same real-time spring motion" },
  { id = "staging_post", clock = TOTAL, file = "core/staging.lua",
    knobs = { "NEURO_POST_PLAY", "NEURO_POST_DISCARD", "NEURO_POST_BUY", "NEURO_POST_SELL",
              "NEURO_POST_DEFAULT" }, wired = true,
    why = "keeps the mod quiet while the action's own animation plays out" },
  { id = "state_cooldown", clock = TOTAL, file = "core/orchestrator.lua",
    knobs = { "NEURO_STATE_COOLDOWN" }, wired = true,
    why = "lets the new state's entry animation start before anything is offered" },
  { id = "state_entry_cooldown", clock = TOTAL, file = "core/orchestrator.lua",
    knob_prefix = "NEURO_ENTRY_CD_", wired = true,
    why = "per-state settle time, sized off how long that state takes to draw itself" },

  { id = "anim_card_beat", clock = REAL, file = "render/neuro-anim.lua", wired = true,
    why = "decorates card motion, and Moveable:move runs on real_dt (dump game.lua:2757-2766), so the beat and the motion must not drift apart" },
  { id = "anim_engine_settle", clock = TOTAL, file = "render/neuro-anim.lua", wired = true,
    why = "waits for E_MANAGER to drain or for the engine to fill an area, and Event's own timer is TOTAL" },
  { id = "anim_commit_lead", clock = TOTAL, file = "render/neuro-anim.lua", wired = true,
    why = "choreography that has to land before a commit core/staging.lua schedules on the game clock" },

  { id = "force_stall", clock = REAL, file = "core/orchestrator.lua",
    knobs = { "NEURO_FORCE_STALL" }, wired = true,
    why = "bounds the mod's own silence, which is owed to the client and must keep running while the game does not" },
  { id = "login_anim_block", clock = REAL, file = "core/orchestrator.lua",
    knobs = { "NEURO_LOGIN_ANIM_BLOCK" }, wired = true,
    why = "gates against the mod's own login animation, which render/neuro-anim.lua draws on REAL" },
  { id = "game_error_log_cooldown", clock = REAL, file = "core/orchestrator.lua", wired = true,
    why = "stdout spam guard; TOTAL stops entirely while the game is paused and the print would not" },
  { id = "neuro_error_log_cooldown", clock = REAL, file = "core/orchestrator.lua", wired = true,
    why = "stdout spam guard, same reason as game_error_log_cooldown" },
  { id = "staging_error_log_cooldown", clock = REAL, file = "core/staging.lua", wired = true,
    why = "stdout spam guard, same reason as game_error_log_cooldown" },
  { id = "ui_text_cache_ttl", clock = REAL, file = "util/utils.lua", wired = true,
    why = "a rebuild-cost cache; its TTL is about frames spent, not about the game advancing" },

  { id = "ack_idle_reask", clock = REAL, file = "core/force_state.lua",
    knobs = { "NEURO_ACK_IDLE_REASK" }, wired = true,
    why = "bounds Neuro's silence on an acknowledged offer; it measures the client, not the game" },
  { id = "force_liveness_timeout", clock = REAL, file = "core/force_state.lua",
    knobs = { "NEURO_FORCE_LIVENESS_TIMEOUT" }, wired = true,
    why = "sized off archived wire latencies, which are wall-clock seconds" },
  { id = "cancel_settle", clock = REAL, file = "core/force_state.lua",
    knobs = { "NEURO_FORCE_CANCEL_SETTLE", "NEURO_FORCE_CANCEL_IDLE" }, wired = true,
    why = "the gap the client needs to drop a withdrawn force, and the cap on how long the post-withdrawal quarantine may wait for a successor; wire properties" },
  { id = "action_dying_grace", clock = WALL, file = "core/action_registry.lua", wired = true,
    why = "how long a just-unregistered name may still arrive from the client, across a run reset" },
  { id = "inbox_poll", clock = WALL, file = "core/bridge.lua", wired = true,
    why = "the rate at which the mod reads the IPC file; unrelated to the game and to the run" },
  { id = "result_deadline", clock = WALL, file = "core/bridge.lua", wired = true,
    why = "the SDK's bound on answering an action, owed to the client and outliving any run" },
  { id = "bridge_transition_cooldown", clock = WALL, file = "core/bridge.lua",
    knobs = { "NEURO_TRANSITION_COOLDOWN" }, wired = true,
    why = "debounces the wire-side state notice; a run reset must not rewind it mid-debounce" },
  { id = "context_refresh_cooldown", clock = REAL, file = "core/enforce.lua",
    knobs = { "NEURO_REFRESH_COOLDOWN" }, wired = true,
    why = "throttles rebuilding the action list; a cost guard, not a wait on the game" },
  { id = "ctx_cache_ttl", clock = REAL, file = "context/context_compact.lua",
    knobs = { "NEURO_CTX_CACHE_TTL" }, wired = true,
    why = "a rebuild-cost cache, same reason as ui_text_cache_ttl" },
  { id = "showcase_grace", clock = REAL, file = "hud/showcase.lua", wired = true,
    why = "the HUD showcase is drawn against REAL, so its claim and removal windows must match" },
  { id = "voucher_drawer_safety", clock = REAL, file = "hud/showcase.lua", wired = true,
    knobs = { "NEURO_VOUCHER_DRAWER_SAFETY" },
    why = "a ceiling on a centre corridor that stopped ticking, and the corridor it watches is drawn on the same clock as showcase_grace" },

  { id = "action_cooldown", clock = TOTAL, file = "core/neuro_lifecycle.lua",
    knobs = { "NEURO_ACTION_COOLDOWN" }, wired = true,
    why = "the gap after an action exists so the action can finish playing" },
  { id = "force_debounce", clock = TOTAL, file = "core/neuro_lifecycle.lua",
    knobs = { "NEURO_FORCE_DEBOUNCE" }, wired = true,
    why = "coalesces force rebuilds triggered by game events" },
  { id = "enforce_per_action_cooldown", clock = TOTAL, file = "core/enforce.lua",
    knobs = { "NEURO_ENFORCE_COOLDOWN" }, wired = true,
    why = "spaces repeats of one action so the game can show each one" },
  { id = "enforce_global_cooldown", clock = TOTAL, file = "core/enforce.lua",
    knobs = { "NEURO_GLOBAL_COOLDOWN" }, wired = true,
    why = "spaces any two actions so the board is settled between them" },
  { id = "enforce_state_throttle", clock = TOTAL, file = "core/enforce.lua",
    knobs = { "NEURO_THROTTLE_SHOP", "NEURO_THROTTLE_PACK",
              "NEURO_GLOBAL_THROTTLE_SELECTING_HAND", "NEURO_GLOBAL_THROTTLE_SHOP",
              "NEURO_GLOBAL_THROTTLE_BLIND_SELECT", "NEURO_GLOBAL_THROTTLE_PACK" }, wired = true,
    why = "per-state pacing sized off how long that state's animations run" },
  { id = "failure_defer_window", clock = TOTAL, file = "core/neuro_lifecycle.lua",
    knobs = { "NEURO_DEFER_WINDOW_MIN", "NEURO_SHOP_BUY_DELAY", "NEURO_PACK_PICK_DELAY" }, wired = true,
    why = "holds a failure notice until the delayed commit event it may describe has fired" },
  { id = "shop_buy_block", clock = TOTAL, file = "handlers/shop_handlers.lua",
    knobs = { "NEURO_SHOP_BUY_BLOCK", "NEURO_SHOP_BUY_DELAY" }, wired = true,
    why = "blocks the shop until the purchase has left the shop area on screen" },
  { id = "shop_buy_watchdog_grace", clock = TOTAL, file = "handlers/shop_handlers.lua",
    knobs = { "NEURO_SHOP_BUY_WATCHDOG_GRACE" }, wired = true,
    why = "slack on the purchase receipt's deadline, which waits on the same animation" },
  { id = "pack_pick_block", clock = TOTAL, file = "handlers/use_card.lua",
    knobs = { "NEURO_PACK_PICK_BLOCK", "NEURO_PACK_PICK_DELAY" }, wired = true,
    why = "blocks the pack until the picked card has landed" },
  { id = "receipt_deadline", clock = TOTAL, file = "core/action_receipt.lua", wired = true,
    why = "a receipt waits for the game to show the action applied" },
}

local by_id = {}
for i = 1, #gates do
  local gate = gates[i]
  assert(gate.clock == REAL or gate.clock == TOTAL or gate.clock == WALL,
    "gate clock must be REAL, TOTAL or WALL: " .. tostring(gate.id))
  assert(not by_id[gate.id], "duplicate gate id: " .. tostring(gate.id))
  assert(gate.wired == true or type(gate.blocked_by) == "string",
    "unwired gate must say what blocks it: " .. tostring(gate.id))
  by_id[gate.id] = gate
end

return {
  REAL = REAL,
  TOTAL = TOTAL,
  WALL = WALL,
  gates = gates,
  by_id = by_id,
  clock_of = function(id)
    local gate = by_id[id]
    assert(gate, "unknown timing gate: " .. tostring(id))
    return gate.clock
  end,
}
