local Filtered = {}

local FILTERED_TERMS = {
  { term = "nigg*", type = "wildcard", action = "block_and_mute" },
  { term = "fagg*", type = "wildcard", action = "block_and_mute" },
  { term = "kike", type = "exact", action = "block_and_mute" },
  { term = "retard", type = "exact", action = "replace", replacement = "idiot" },
  { term = "2 girls 1 cup", type = "exact", action = "block_and_mute" },
  { term = "anal", type = "exact", action = "block_and_mute" },
  { term = "anus", type = "exact", action = "block_and_mute" },
  { term = "areole", type = "exact", action = "block_and_mute" },
  { term = "arian", type = "exact", action = "block_and_mute" },
  { term = "arrse", type = "exact", action = "block_and_mute" },
  { term = "arse", type = "exact", action = "block_and_mute" },
  { term = "arsehole", type = "exact", action = "block_and_mute" },
  { term = "aryan", type = "exact", action = "block_and_mute" },
  { term = "asanchez", type = "exact", action = "block_and_mute" },
  { term = "ass", type = "exact", action = "block_and_mute" },
  { term = "assbang", type = "exact", action = "block_and_mute" },
  { term = "assbanged", type = "exact", action = "block_and_mute" },
  { term = "asses", type = "exact", action = "block_and_mute" },
  { term = "assfuck", type = "exact", action = "block_and_mute" },
  { term = "assfucker", type = "exact", action = "block_and_mute" },
  { term = "assfukka", type = "exact", action = "block_and_mute" },
  { term = "asshole", type = "exact", action = "block_and_mute" },
  { term = "assmunch", type = "exact", action = "block_and_mute" },
  { term = "asswhole", type = "exact", action = "block_and_mute" },
  { term = "autoerotic", type = "exact", action = "block_and_mute" },
  { term = "ballsack", type = "exact", action = "block_and_mute" },
  { term = "bastard", type = "exact", action = "block_and_mute" },
  { term = "bdsm", type = "exact", action = "block_and_mute" },
  { term = "beastial", type = "exact", action = "block_and_mute" },
  { term = "beastiality", type = "exact", action = "block_and_mute" },
  { term = "bellend", type = "exact", action = "block_and_mute" },
  { term = "bestial", type = "exact", action = "block_and_mute" },
  { term = "bestiality", type = "exact", action = "block_and_mute" },
  { term = "bimbo", type = "exact", action = "block_and_mute" },
  { term = "bimbos", type = "exact", action = "block_and_mute" },
  { term = "bitch", type = "exact", action = "block_and_mute" },
  { term = "bitches", type = "exact", action = "block_and_mute" },
  { term = "bitchin", type = "exact", action = "block_and_mute" },
  { term = "bitching", type = "exact", action = "block_and_mute" },
  { term = "blowjob", type = "exact", action = "block_and_mute" },
  { term = "blowjobs", type = "exact", action = "block_and_mute" },
  { term = "blue waffle", type = "exact", action = "block_and_mute" },
  { term = "bondage", type = "exact", action = "block_and_mute" },
  { term = "boner", type = "exact", action = "block_and_mute" },
  { term = "boob", type = "exact", action = "block_and_mute" },
  { term = "boobs", type = "exact", action = "block_and_mute" },
  { term = "booobs", type = "exact", action = "block_and_mute" },
  { term = "boooobs", type = "exact", action = "block_and_mute" },
  { term = "booooobs", type = "exact", action = "block_and_mute" },
  { term = "booooooobs", type = "exact", action = "block_and_mute" },
  { term = "booty call", type = "exact", action = "block_and_mute" },
  { term = "breasts", type = "exact", action = "block_and_mute" },
  { term = "brown shower", type = "exact", action = "block_and_mute" },
  { term = "brown showers", type = "exact", action = "block_and_mute" },
  { term = "buceta", type = "exact", action = "block_and_mute" },
  { term = "bukake", type = "exact", action = "block_and_mute" },
  { term = "bukkake", type = "exact", action = "block_and_mute" },
  { term = "bullshit", type = "exact", action = "block_and_mute" },
  { term = "busty", type = "exact", action = "block_and_mute" },
  { term = "butthole", type = "exact", action = "block_and_mute" },
  { term = "carpet muncher", type = "exact", action = "block_and_mute" },
  { term = "cawk", type = "exact", action = "block_and_mute" },
  { term = "chink", type = "exact", action = "block_and_mute" },
  { term = "cipa", type = "exact", action = "block_and_mute" },
  { term = "clit", type = "exact", action = "block_and_mute" },
  { term = "clitoris", type = "exact", action = "block_and_mute" },
  { term = "clits", type = "exact", action = "block_and_mute" },
  { term = "cnut", type = "exact", action = "block_and_mute" },
  { term = "cock", type = "exact", action = "block_and_mute" },
  { term = "cockface", type = "exact", action = "block_and_mute" },
  { term = "cockhead", type = "exact", action = "block_and_mute" },
  { term = "cockmunch", type = "exact", action = "block_and_mute" },
  { term = "cockmuncher", type = "exact", action = "block_and_mute" },
  { term = "cocks", type = "exact", action = "block_and_mute" },
  { term = "cocksuck", type = "exact", action = "block_and_mute" },
  { term = "cocksucked", type = "exact", action = "block_and_mute" },
  { term = "cocksucker", type = "exact", action = "block_and_mute" },
  { term = "cocksucking", type = "exact", action = "block_and_mute" },
  { term = "cocksucks", type = "exact", action = "block_and_mute" },
  { term = "cokmuncher", type = "exact", action = "block_and_mute" },
  { term = "coon", type = "exact", action = "block_and_mute" },
  { term = "cowgirl", type = "exact", action = "block_and_mute" },
  { term = "cowgirls", type = "exact", action = "block_and_mute" },
  { term = "crotch", type = "exact", action = "block_and_mute" },
  { term = "cum", type = "exact", action = "block_and_mute" },
  { term = "cuming", type = "exact", action = "block_and_mute" },
  { term = "cummer", type = "exact", action = "block_and_mute" },
  { term = "cumming", type = "exact", action = "block_and_mute" },
  { term = "cums", type = "exact", action = "block_and_mute" },
  { term = "cumshot", type = "exact", action = "block_and_mute" },
  { term = "cunilingus", type = "exact", action = "block_and_mute" },
  { term = "cunillingus", type = "exact", action = "block_and_mute" },
  { term = "cunnilingus", type = "exact", action = "block_and_mute" },
  { term = "cunt", type = "exact", action = "block_and_mute" },
  { term = "cuntlicker", type = "exact", action = "block_and_mute" },
  { term = "cuntlicking", type = "exact", action = "block_and_mute" },
  { term = "cunts", type = "exact", action = "block_and_mute" },
  { term = "deepthroat", type = "exact", action = "block_and_mute" },
  { term = "dick", type = "exact", action = "block_and_mute" },
  { term = "dickhead", type = "exact", action = "block_and_mute" },
  { term = "dildo", type = "exact", action = "block_and_mute" },
  { term = "dildos", type = "exact", action = "block_and_mute" },
  { term = "dink", type = "exact", action = "block_and_mute" },
  { term = "dinks", type = "exact", action = "block_and_mute" },
  { term = "dlck", type = "exact", action = "block_and_mute" },
  { term = "dog style", type = "exact", action = "block_and_mute" },
  { term = "dog-fucker", type = "exact", action = "block_and_mute" },
  { term = "doggiestyle", type = "exact", action = "block_and_mute" },
  { term = "doggin", type = "exact", action = "block_and_mute" },
  { term = "dogging", type = "exact", action = "block_and_mute" },
  { term = "doggystyle", type = "exact", action = "block_and_mute" },
  { term = "dong", type = "exact", action = "block_and_mute" },
  { term = "donkeyribber", type = "exact", action = "block_and_mute" },
  { term = "doosh", type = "exact", action = "block_and_mute" },
  { term = "dopey", type = "exact", action = "block_and_mute" },
  { term = "douche", type = "exact", action = "block_and_mute" },
  { term = "douchebag", type = "exact", action = "block_and_mute" },
  { term = "douchebags", type = "exact", action = "block_and_mute" },
  { term = "douchey", type = "exact", action = "block_and_mute" },
  { term = "duche", type = "exact", action = "block_and_mute" },
  { term = "dumass", type = "exact", action = "block_and_mute" },
  { term = "dumbass", type = "exact", action = "block_and_mute" },
  { term = "dumbasses", type = "exact", action = "block_and_mute" },
  { term = "dyke", type = "exact", action = "block_and_mute" },
  { term = "dykes", type = "exact", action = "block_and_mute" },
  { term = "eatadick", type = "exact", action = "block_and_mute" },
  { term = "eathairpie", type = "exact", action = "block_and_mute" },
  { term = "ejaculate", type = "exact", action = "block_and_mute" },
  { term = "ejaculated", type = "exact", action = "block_and_mute" },
  { term = "ejaculates", type = "exact", action = "block_and_mute" },
  { term = "ejaculating", type = "exact", action = "block_and_mute" },
  { term = "ejaculatings", type = "exact", action = "block_and_mute" },
  { term = "ejaculation", type = "exact", action = "block_and_mute" },
  { term = "ejakulate", type = "exact", action = "block_and_mute" },
  { term = "enlargement", type = "exact", action = "block_and_mute" },
  { term = "erect", type = "exact", action = "block_and_mute" },
  { term = "erection", type = "exact", action = "block_and_mute" },
  { term = "erotic", type = "exact", action = "block_and_mute" },
  { term = "erotism", type = "exact", action = "block_and_mute" },
  { term = "essohbee", type = "exact", action = "block_and_mute" },
  { term = "extacy", type = "exact", action = "block_and_mute" },
  { term = "extasy", type = "exact", action = "block_and_mute" },
  { term = "facial", type = "exact", action = "block_and_mute" },
  { term = "fack", type = "exact", action = "block_and_mute" },
  { term = "fag", type = "exact", action = "block_and_mute" },
  { term = "fagg", type = "exact", action = "block_and_mute" },
  { term = "fagged", type = "exact", action = "block_and_mute" },
  { term = "fagging", type = "exact", action = "block_and_mute" },
  { term = "faggit", type = "exact", action = "block_and_mute" },
  { term = "faggitt", type = "exact", action = "block_and_mute" },
  { term = "faggot", type = "exact", action = "block_and_mute" },
  { term = "faggs", type = "exact", action = "block_and_mute" },
  { term = "fagot", type = "exact", action = "block_and_mute" },
  { term = "fagots", type = "exact", action = "block_and_mute" },
  { term = "fags", type = "exact", action = "block_and_mute" },
  { term = "faig", type = "exact", action = "block_and_mute" },
  { term = "faigt", type = "exact", action = "block_and_mute" },
  { term = "fanny", type = "exact", action = "block_and_mute" },
  { term = "fannybandit", type = "exact", action = "block_and_mute" },
  { term = "fannyflaps", type = "exact", action = "block_and_mute" },
  { term = "fannyfucker", type = "exact", action = "block_and_mute" },
  { term = "fanyy", type = "exact", action = "block_and_mute" },
  { term = "fart", type = "exact", action = "block_and_mute" },
  { term = "fartknocker", type = "exact", action = "block_and_mute" },
  { term = "fat", type = "exact", action = "block_and_mute" },
  { term = "fatass", type = "exact", action = "block_and_mute" },
  { term = "fcuk", type = "exact", action = "block_and_mute" },
  { term = "fcuker", type = "exact", action = "block_and_mute" },
  { term = "fcuking", type = "exact", action = "block_and_mute" },
  { term = "feck", type = "exact", action = "block_and_mute" },
  { term = "fecker", type = "exact", action = "block_and_mute" },
  { term = "felch", type = "exact", action = "block_and_mute" },
  { term = "felcher", type = "exact", action = "block_and_mute" },
  { term = "felching", type = "exact", action = "block_and_mute" },
  { term = "fellate", type = "exact", action = "block_and_mute" },
  { term = "fellatio", type = "exact", action = "block_and_mute" },
  { term = "feltch", type = "exact", action = "block_and_mute" },
  { term = "feltcher", type = "exact", action = "block_and_mute" },
  { term = "femdom", type = "exact", action = "block_and_mute" },
  { term = "fingerfuck", type = "exact", action = "block_and_mute" },
  { term = "fingerfucked", type = "exact", action = "block_and_mute" },
  { term = "fingerfucker", type = "exact", action = "block_and_mute" },
  { term = "fingerfuckers", type = "exact", action = "block_and_mute" },
  { term = "fingerfucking", type = "exact", action = "block_and_mute" },
  { term = "fingerfucks", type = "exact", action = "block_and_mute" },
  { term = "fingering", type = "exact", action = "block_and_mute" },
  { term = "fisted", type = "exact", action = "block_and_mute" },
  { term = "fistfuck", type = "exact", action = "block_and_mute" },
  { term = "fistfucked", type = "exact", action = "block_and_mute" },
  { term = "fistfucker", type = "exact", action = "block_and_mute" },
  { term = "fistfuckers", type = "exact", action = "block_and_mute" },
  { term = "fistfucking", type = "exact", action = "block_and_mute" },
  { term = "fistfuckings", type = "exact", action = "block_and_mute" },
  { term = "fistfucks", type = "exact", action = "block_and_mute" },
  { term = "fisting", type = "exact", action = "block_and_mute" },
  { term = "fisty", type = "exact", action = "block_and_mute" },
  { term = "flange", type = "exact", action = "block_and_mute" },
  { term = "flogthelog", type = "exact", action = "block_and_mute" },
  { term = "floozy", type = "exact", action = "block_and_mute" },
  { term = "foad", type = "exact", action = "block_and_mute" },
  { term = "fondle", type = "exact", action = "block_and_mute" },
  { term = "foobar", type = "exact", action = "block_and_mute" },
  { term = "fook", type = "exact", action = "block_and_mute" },
  { term = "fooker", type = "exact", action = "block_and_mute" },
  { term = "footjob", type = "exact", action = "block_and_mute" },
  { term = "foreskin", type = "exact", action = "block_and_mute" },
  { term = "freex", type = "exact", action = "block_and_mute" },
  { term = "frigg", type = "exact", action = "block_and_mute" },
  { term = "frigga", type = "exact", action = "block_and_mute" },
  { term = "fubar", type = "exact", action = "block_and_mute" },
  { term = "fuck", type = "exact", action = "block_and_mute" },
  { term = "fucka", type = "exact", action = "block_and_mute" },
  { term = "fuckass", type = "exact", action = "block_and_mute" },
  { term = "fuckbitch", type = "exact", action = "block_and_mute" },
  { term = "fucked", type = "exact", action = "block_and_mute" },
  { term = "fucker", type = "exact", action = "block_and_mute" },
  { term = "fuckers", type = "exact", action = "block_and_mute" },
  { term = "fuckface", type = "exact", action = "block_and_mute" },
  { term = "fuckhead", type = "exact", action = "block_and_mute" },
  { term = "fuckheads", type = "exact", action = "block_and_mute" },
  { term = "fuckhole", type = "exact", action = "block_and_mute" },
  { term = "fuckin", type = "exact", action = "block_and_mute" },
  { term = "fucking", type = "exact", action = "block_and_mute" },
  { term = "fuckings", type = "exact", action = "block_and_mute" },
  { term = "fuckingshitmotherfucker", type = "exact", action = "block_and_mute" },
  { term = "fuckme", type = "exact", action = "block_and_mute" },
  { term = "fuckmeat", type = "exact", action = "block_and_mute" },
  { term = "fucknugget", type = "exact", action = "block_and_mute" },
  { term = "fucknut", type = "exact", action = "block_and_mute" },
  { term = "fuckoff", type = "exact", action = "block_and_mute" },
  { term = "fuckpuppet", type = "exact", action = "block_and_mute" },
  { term = "fucks", type = "exact", action = "block_and_mute" },
  { term = "fucktard", type = "exact", action = "block_and_mute" },
  { term = "fucktoy", type = "exact", action = "block_and_mute" },
  { term = "fucktrophy", type = "exact", action = "block_and_mute" },
  { term = "fuckup", type = "exact", action = "block_and_mute" },
  { term = "fuckwad", type = "exact", action = "block_and_mute" },
  { term = "fuckwhit", type = "exact", action = "block_and_mute" },
  { term = "fuckwit", type = "exact", action = "block_and_mute" },
  { term = "fuckyomama", type = "exact", action = "block_and_mute" },
  { term = "fudgepacker", type = "exact", action = "block_and_mute" },
  { term = "fuk", type = "exact", action = "block_and_mute" },
  { term = "fuker", type = "exact", action = "block_and_mute" },
  { term = "fukker", type = "exact", action = "block_and_mute" },
  { term = "fukkin", type = "exact", action = "block_and_mute" },
  { term = "fukking", type = "exact", action = "block_and_mute" },
  { term = "fuks", type = "exact", action = "block_and_mute" },
  { term = "fukwhit", type = "exact", action = "block_and_mute" },
  { term = "fukwit", type = "exact", action = "block_and_mute" },
  { term = "futanari", type = "exact", action = "block_and_mute" },
  { term = "futanary", type = "exact", action = "block_and_mute" },
  { term = "fux", type = "exact", action = "block_and_mute" },
  { term = "fuxor", type = "exact", action = "block_and_mute" },
  { term = "fxck", type = "exact", action = "block_and_mute" },
  { term = "gae", type = "exact", action = "block_and_mute" },
  { term = "gai", type = "exact", action = "block_and_mute" },
  { term = "gangbang", type = "exact", action = "block_and_mute" },
  { term = "gangbanged", type = "exact", action = "block_and_mute" },
  { term = "gangbangs", type = "exact", action = "block_and_mute" },
  { term = "ganja", type = "exact", action = "block_and_mute" },
  { term = "gassyass", type = "exact", action = "block_and_mute" },
  { term = "gay", type = "exact", action = "block_and_mute" },
  { term = "gaylord", type = "exact", action = "block_and_mute" },
  { term = "gays", type = "exact", action = "block_and_mute" },
  { term = "gaysex", type = "exact", action = "block_and_mute" },
  { term = "gey", type = "exact", action = "block_and_mute" },
  { term = "gfy", type = "exact", action = "block_and_mute" },
  { term = "ghay", type = "exact", action = "block_and_mute" },
  { term = "ghey", type = "exact", action = "block_and_mute" },
  { term = "gigolo", type = "exact", action = "block_and_mute" },
  { term = "glans", type = "exact", action = "block_and_mute" },
  { term = "goatse", type = "exact", action = "block_and_mute" },
  { term = "god", type = "exact", action = "block_and_mute" },
  { term = "godamn", type = "exact", action = "block_and_mute" },
  { term = "godamnit", type = "exact", action = "block_and_mute" },
  { term = "goddam", type = "exact", action = "block_and_mute" },
  { term = "goddammit", type = "exact", action = "block_and_mute" },
  { term = "goddamn", type = "exact", action = "block_and_mute" },
  { term = "goddamned", type = "exact", action = "block_and_mute" },
  { term = "gokkun", type = "exact", action = "block_and_mute" },
  { term = "goldenshower", type = "exact", action = "block_and_mute" },
  { term = "gonad", type = "exact", action = "block_and_mute" },
  { term = "gonads", type = "exact", action = "block_and_mute" },
  { term = "gook", type = "exact", action = "block_and_mute" },
  { term = "gooks", type = "exact", action = "block_and_mute" },
  { term = "gringo", type = "exact", action = "block_and_mute" },
  { term = "gspot", type = "exact", action = "block_and_mute" },
  { term = "gtfo", type = "exact", action = "block_and_mute" },
  { term = "guido", type = "exact", action = "block_and_mute" },
  { term = "hamflap", type = "exact", action = "block_and_mute" },
  { term = "handjob", type = "exact", action = "block_and_mute" },
  { term = "hardcoresex", type = "exact", action = "block_and_mute" },
  { term = "hardon", type = "exact", action = "block_and_mute" },
  { term = "hebe", type = "exact", action = "block_and_mute" },
  { term = "heeb", type = "exact", action = "block_and_mute" },
  { term = "hemp", type = "exact", action = "block_and_mute" },
  { term = "hentai", type = "exact", action = "block_and_mute" },
  { term = "heroin", type = "exact", action = "block_and_mute" },
  { term = "herp", type = "exact", action = "block_and_mute" },
  { term = "herpes", type = "exact", action = "block_and_mute" },
  { term = "herpy", type = "exact", action = "block_and_mute" },
  { term = "heshe", type = "exact", action = "block_and_mute" },
  { term = "hitler", type = "exact", action = "block_and_mute" },
  { term = "hiv", type = "exact", action = "block_and_mute" },
  { term = "hoar", type = "exact", action = "block_and_mute" },
  { term = "hoare", type = "exact", action = "block_and_mute" },
  { term = "hobag", type = "exact", action = "block_and_mute" },
  { term = "hoer", type = "exact", action = "block_and_mute" },
  { term = "homey", type = "exact", action = "block_and_mute" },
  { term = "homo", type = "exact", action = "block_and_mute" },
  { term = "homoerotic", type = "exact", action = "block_and_mute" },
  { term = "homoey", type = "exact", action = "block_and_mute" },
  { term = "honky", type = "exact", action = "block_and_mute" },
  { term = "hooch", type = "exact", action = "block_and_mute" },
  { term = "hookah", type = "exact", action = "block_and_mute" },
  { term = "hooker", type = "exact", action = "block_and_mute" },
  { term = "hoor", type = "exact", action = "block_and_mute" },
  { term = "hootch", type = "exact", action = "block_and_mute" },
  { term = "hooter", type = "exact", action = "block_and_mute" },
  { term = "hooters", type = "exact", action = "block_and_mute" },
  { term = "hore", type = "exact", action = "block_and_mute" },
  { term = "horniest", type = "exact", action = "block_and_mute" },
  { term = "horny", type = "exact", action = "block_and_mute" },
  { term = "hotsex", type = "exact", action = "block_and_mute" },
  { term = "howtokill", type = "exact", action = "block_and_mute" },
  { term = "howtomurdep", type = "exact", action = "block_and_mute" },
  { term = "hump", type = "exact", action = "block_and_mute" },
  { term = "humped", type = "exact", action = "block_and_mute" },
  { term = "humping", type = "exact", action = "block_and_mute" },
  { term = "hussy", type = "exact", action = "block_and_mute" },
  { term = "hymen", type = "exact", action = "block_and_mute" },
  { term = "inbred", type = "exact", action = "block_and_mute" },
  { term = "incest", type = "exact", action = "block_and_mute" },
  { term = "injun", type = "exact", action = "block_and_mute" },
  { term = "jackass", type = "exact", action = "block_and_mute" },
  { term = "jackhole", type = "exact", action = "block_and_mute" },
  { term = "jackoff", type = "exact", action = "block_and_mute" },
  { term = "jap", type = "exact", action = "block_and_mute" },
  { term = "japs", type = "exact", action = "block_and_mute" },
  { term = "jerked", type = "exact", action = "block_and_mute" },
  { term = "jerkoff", type = "exact", action = "block_and_mute" },
  { term = "jism", type = "exact", action = "block_and_mute" },
  { term = "jiz", type = "exact", action = "block_and_mute" },
  { term = "jizm", type = "exact", action = "block_and_mute" },
  { term = "jizz", type = "exact", action = "block_and_mute" },
  { term = "jizzed", type = "exact", action = "block_and_mute" },
  { term = "junkie", type = "exact", action = "block_and_mute" },
  { term = "junky", type = "exact", action = "block_and_mute" },
  { term = "kawk", type = "exact", action = "block_and_mute" },
  { term = "kikes", type = "exact", action = "block_and_mute" },
  { term = "kill", type = "exact", action = "block_and_mute" },
  { term = "kinbaku", type = "exact", action = "block_and_mute" },
  { term = "kinky", type = "exact", action = "block_and_mute" },
  { term = "kinkyJesus", type = "exact", action = "block_and_mute" },
  { term = "kkk", type = "exact", action = "block_and_mute" },
  { term = "klan", type = "exact", action = "block_and_mute" },
  { term = "knob", type = "exact", action = "block_and_mute" },
  { term = "knobead", type = "exact", action = "block_and_mute" },
  { term = "knobed", type = "exact", action = "block_and_mute" },
  { term = "knobend", type = "exact", action = "block_and_mute" },
  { term = "knobhead", type = "exact", action = "block_and_mute" },
  { term = "knobjocky", type = "exact", action = "block_and_mute" },
  { term = "knobjokey", type = "exact", action = "block_and_mute" },
  { term = "kock", type = "exact", action = "block_and_mute" },
  { term = "kondum", type = "exact", action = "block_and_mute" },
  { term = "kondums", type = "exact", action = "block_and_mute" },
  { term = "kooch", type = "exact", action = "block_and_mute" },
  { term = "kooches", type = "exact", action = "block_and_mute" },
  { term = "kootch", type = "exact", action = "block_and_mute" },
  { term = "kraut", type = "exact", action = "block_and_mute" },
  { term = "kum", type = "exact", action = "block_and_mute" },
  { term = "kummer", type = "exact", action = "block_and_mute" },
  { term = "kumming", type = "exact", action = "block_and_mute" },
  { term = "kums", type = "exact", action = "block_and_mute" },
  { term = "kunilingus", type = "exact", action = "block_and_mute" },
  { term = "kwif", type = "exact", action = "block_and_mute" },
  { term = "kyke", type = "exact", action = "block_and_mute" },
  { term = "l3itch", type = "exact", action = "block_and_mute" },
  { term = "labia", type = "exact", action = "block_and_mute" },
  { term = "lech", type = "exact", action = "block_and_mute" },
  { term = "len", type = "exact", action = "block_and_mute" },
  { term = "leper", type = "exact", action = "block_and_mute" },
  { term = "lesbians", type = "exact", action = "block_and_mute" },
  { term = "lesbo", type = "exact", action = "block_and_mute" },
  { term = "lesbos", type = "exact", action = "block_and_mute" },
  { term = "lez", type = "exact", action = "block_and_mute" },
  { term = "lezbian", type = "exact", action = "block_and_mute" },
  { term = "lezbians", type = "exact", action = "block_and_mute" },
  { term = "lezbo", type = "exact", action = "block_and_mute" },
  { term = "lezbos", type = "exact", action = "block_and_mute" },
  { term = "lezzie", type = "exact", action = "block_and_mute" },
  { term = "lezzies", type = "exact", action = "block_and_mute" },
  { term = "lezzy", type = "exact", action = "block_and_mute" },
  { term = "loin", type = "exact", action = "block_and_mute" },
  { term = "loins", type = "exact", action = "block_and_mute" },
  { term = "lube", type = "exact", action = "block_and_mute" },
  { term = "lust", type = "exact", action = "block_and_mute" },
  { term = "lusting", type = "exact", action = "block_and_mute" },
  { term = "lusty", type = "exact", action = "block_and_mute" },
  { term = "m-fucking", type = "exact", action = "block_and_mute" },
  { term = "mafugly", type = "exact", action = "block_and_mute" },
  { term = "mams", type = "exact", action = "block_and_mute" },
  { term = "masochist", type = "exact", action = "block_and_mute" },
  { term = "massa", type = "exact", action = "block_and_mute" },
  { term = "masterb8", type = "exact", action = "block_and_mute" },
  { term = "masterbate", type = "exact", action = "block_and_mute" },
  { term = "masterbating", type = "exact", action = "block_and_mute" },
  { term = "masterbation", type = "exact", action = "block_and_mute" },
  { term = "masterbations", type = "exact", action = "block_and_mute" },
  { term = "masturbate", type = "exact", action = "block_and_mute" },
  { term = "masturbating", type = "exact", action = "block_and_mute" },
  { term = "masturbation", type = "exact", action = "block_and_mute" },
  { term = "maxi", type = "exact", action = "block_and_mute" },
  { term = "menses", type = "exact", action = "block_and_mute" },
  { term = "menstruate", type = "exact", action = "block_and_mute" },
  { term = "menstruation", type = "exact", action = "block_and_mute" },
  { term = "meth", type = "exact", action = "block_and_mute" },
  { term = "milf", type = "exact", action = "block_and_mute" },
  { term = "mofo", type = "exact", action = "block_and_mute" },
  { term = "molest", type = "exact", action = "block_and_mute" },
  { term = "moolie", type = "exact", action = "block_and_mute" },
  { term = "mothafuck", type = "exact", action = "block_and_mute" },
  { term = "mothafucka", type = "exact", action = "block_and_mute" },
  { term = "mothafuckas", type = "exact", action = "block_and_mute" },
  { term = "mothafuckaz", type = "exact", action = "block_and_mute" },
  { term = "mothafucked", type = "exact", action = "block_and_mute" },
  { term = "mothafucker", type = "exact", action = "block_and_mute" },
  { term = "mothafuckers", type = "exact", action = "block_and_mute" },
  { term = "mothafuckin", type = "exact", action = "block_and_mute" },
  { term = "mothafucking", type = "exact", action = "block_and_mute" },
  { term = "mothafuckings", type = "exact", action = "block_and_mute" },
  { term = "mothafucks", type = "exact", action = "block_and_mute" },
  { term = "motherfuck", type = "exact", action = "block_and_mute" },
  { term = "motherfucka", type = "exact", action = "block_and_mute" },
  { term = "motherfucked", type = "exact", action = "block_and_mute" },
  { term = "motherfucker", type = "exact", action = "block_and_mute" },
  { term = "motherfuckers", type = "exact", action = "block_and_mute" },
  { term = "motherfuckin", type = "exact", action = "block_and_mute" },
  { term = "motherfucking", type = "exact", action = "block_and_mute" },
  { term = "motherfuckings", type = "exact", action = "block_and_mute" },
  { term = "motherfuckka", type = "exact", action = "block_and_mute" },
  { term = "motherfucks", type = "exact", action = "block_and_mute" },
  { term = "mtherfucker", type = "exact", action = "block_and_mute" },
  { term = "mthrfucker", type = "exact", action = "block_and_mute" },
  { term = "mthrfucking", type = "exact", action = "block_and_mute" },
  { term = "muff", type = "exact", action = "block_and_mute" },
  { term = "muffdiver", type = "exact", action = "block_and_mute" },
  { term = "muffpuff", type = "exact", action = "block_and_mute" },
  { term = "murder", type = "exact", action = "block_and_mute" },
  { term = "mutha", type = "exact", action = "block_and_mute" },
  { term = "muthafecker", type = "exact", action = "block_and_mute" },
  { term = "muthafuckaz", type = "exact", action = "block_and_mute" },
  { term = "muthafucker", type = "exact", action = "block_and_mute" },
  { term = "muthafuckker", type = "exact", action = "block_and_mute" },
  { term = "muther", type = "exact", action = "block_and_mute" },
  { term = "mutherfucker", type = "exact", action = "block_and_mute" },
  { term = "mutherfucking", type = "exact", action = "block_and_mute" },
  { term = "muthrfucking", type = "exact", action = "block_and_mute" },
  { term = "nad", type = "exact", action = "block_and_mute" },
  { term = "nads", type = "exact", action = "block_and_mute" },
  { term = "naked", type = "exact", action = "block_and_mute" },
  { term = "napalm", type = "exact", action = "block_and_mute" },
  { term = "nappy", type = "exact", action = "block_and_mute" },
  { term = "nazi", type = "exact", action = "block_and_mute" },
  { term = "nazism", type = "exact", action = "block_and_mute" },
  { term = "needthedick", type = "exact", action = "block_and_mute" },
  { term = "negro", type = "exact", action = "block_and_mute" },
  { term = "nig", type = "exact", action = "block_and_mute" },
  { term = "nigg", type = "exact", action = "block_and_mute" },
  { term = "nigga", type = "exact", action = "block_and_mute" },
  { term = "niggah", type = "exact", action = "block_and_mute" },
  { term = "niggas", type = "exact", action = "block_and_mute" },
  { term = "niggaz", type = "exact", action = "block_and_mute" },
  { term = "nigger", type = "exact", action = "block_and_mute" },
  { term = "niggers", type = "exact", action = "block_and_mute" },
  { term = "niggle", type = "exact", action = "block_and_mute" },
  { term = "niglet", type = "exact", action = "block_and_mute" },
  { term = "nimrod", type = "exact", action = "block_and_mute" },
  { term = "ninny", type = "exact", action = "block_and_mute" },
  { term = "nipple", type = "exact", action = "block_and_mute" },
  { term = "nipples", type = "exact", action = "block_and_mute" },
  { term = "nob", type = "exact", action = "block_and_mute" },
  { term = "nobhead", type = "exact", action = "block_and_mute" },
  { term = "nobjocky", type = "exact", action = "block_and_mute" },
  { term = "nobjokey", type = "exact", action = "block_and_mute" },
  { term = "nooky", type = "exact", action = "block_and_mute" },
  { term = "nude", type = "exact", action = "block_and_mute" },
  { term = "nudes", type = "exact", action = "block_and_mute" },
  { term = "numbnuts", type = "exact", action = "block_and_mute" },
  { term = "nutbutter", type = "exact", action = "block_and_mute" },
  { term = "nutsack", type = "exact", action = "block_and_mute" },
  { term = "nympho", type = "exact", action = "block_and_mute" },
  { term = "opiate", type = "exact", action = "block_and_mute" },
  { term = "opium", type = "exact", action = "block_and_mute" },
  { term = "oral", type = "exact", action = "block_and_mute" },
  { term = "orally", type = "exact", action = "block_and_mute" },
  { term = "organ", type = "exact", action = "block_and_mute" },
  { term = "orgasim", type = "exact", action = "block_and_mute" },
  { term = "orgasims", type = "exact", action = "block_and_mute" },
  { term = "orgasm", type = "exact", action = "block_and_mute" },
  { term = "orgasmic", type = "exact", action = "block_and_mute" },
  { term = "orgasms", type = "exact", action = "block_and_mute" },
  { term = "orgies", type = "exact", action = "block_and_mute" },
  { term = "orgy", type = "exact", action = "block_and_mute" },
  { term = "ovary", type = "exact", action = "block_and_mute" },
  { term = "ovum", type = "exact", action = "block_and_mute" },
  { term = "ovums", type = "exact", action = "block_and_mute" },
  { term = "paddy", type = "exact", action = "block_and_mute" },
  { term = "paki", type = "exact", action = "block_and_mute" },
  { term = "pantie", type = "exact", action = "block_and_mute" },
  { term = "panties", type = "exact", action = "block_and_mute" },
  { term = "panty", type = "exact", action = "block_and_mute" },
  { term = "pastie", type = "exact", action = "block_and_mute" },
  { term = "pasty", type = "exact", action = "block_and_mute" },
  { term = "pawn", type = "exact", action = "block_and_mute" },
  { term = "pcp", type = "exact", action = "block_and_mute" },
  { term = "pecker", type = "exact", action = "block_and_mute" },
  { term = "pedo", type = "exact", action = "block_and_mute" },
  { term = "pedophile", type = "exact", action = "block_and_mute" },
  { term = "pedophilia", type = "exact", action = "block_and_mute" },
  { term = "pedophiliac", type = "exact", action = "block_and_mute" },
  { term = "pee", type = "exact", action = "block_and_mute" },
  { term = "peepee", type = "exact", action = "block_and_mute" },
  { term = "penetrate", type = "exact", action = "block_and_mute" },
  { term = "penetration", type = "exact", action = "block_and_mute" },
  { term = "penial", type = "exact", action = "block_and_mute" },
  { term = "penile", type = "exact", action = "block_and_mute" },
  { term = "penis", type = "exact", action = "block_and_mute" },
  { term = "penisfucker", type = "exact", action = "block_and_mute" },
  { term = "perversion", type = "exact", action = "block_and_mute" },
  { term = "peyote", type = "exact", action = "block_and_mute" },
  { term = "phalli", type = "exact", action = "block_and_mute" },
  { term = "phallic", type = "exact", action = "block_and_mute" },
  { term = "phonesex", type = "exact", action = "block_and_mute" },
  { term = "phuck", type = "exact", action = "block_and_mute" },
  { term = "phuk", type = "exact", action = "block_and_mute" },
  { term = "phuked", type = "exact", action = "block_and_mute" },
  { term = "phuking", type = "exact", action = "block_and_mute" },
  { term = "phukked", type = "exact", action = "block_and_mute" },
  { term = "phukking", type = "exact", action = "block_and_mute" },
  { term = "phuks", type = "exact", action = "block_and_mute" },
  { term = "phuq", type = "exact", action = "block_and_mute" },
  { term = "pigfucker", type = "exact", action = "block_and_mute" },
  { term = "pillowbiter", type = "exact", action = "block_and_mute" },
  { term = "pimp", type = "exact", action = "block_and_mute" },
  { term = "pimpis", type = "exact", action = "block_and_mute" },
  { term = "pinko", type = "exact", action = "block_and_mute" },
  { term = "piss", type = "exact", action = "block_and_mute" },
  { term = "pissed", type = "exact", action = "block_and_mute" },
  { term = "pisser", type = "exact", action = "block_and_mute" },
  { term = "pissers", type = "exact", action = "block_and_mute" },
  { term = "pisses", type = "exact", action = "block_and_mute" },
  { term = "pissflaps", type = "exact", action = "block_and_mute" },
  { term = "pissin", type = "exact", action = "block_and_mute" },
  { term = "pissing", type = "exact", action = "block_and_mute" },
  { term = "pissoff", type = "exact", action = "block_and_mute" },
  { term = "playboy", type = "exact", action = "block_and_mute" },
  { term = "pms", type = "exact", action = "block_and_mute" },
  { term = "polack", type = "exact", action = "block_and_mute" },
  { term = "pollock", type = "exact", action = "block_and_mute" },
  { term = "poon", type = "exact", action = "block_and_mute" },
  { term = "poontang", type = "exact", action = "block_and_mute" },
  { term = "poop", type = "exact", action = "block_and_mute" },
  { term = "porn", type = "exact", action = "block_and_mute" },
  { term = "porno", type = "exact", action = "block_and_mute" },
  { term = "pornography", type = "exact", action = "block_and_mute" },
  { term = "pornos", type = "exact", action = "block_and_mute" },
  { term = "pot", type = "exact", action = "block_and_mute" },
  { term = "potty", type = "exact", action = "block_and_mute" },
  { term = "prick", type = "exact", action = "block_and_mute" },
  { term = "pricks", type = "exact", action = "block_and_mute" },
  { term = "prig", type = "exact", action = "block_and_mute" },
  { term = "pron", type = "exact", action = "block_and_mute" },
  { term = "prostitute", type = "exact", action = "block_and_mute" },
  { term = "prude", type = "exact", action = "block_and_mute" },
  { term = "pube", type = "exact", action = "block_and_mute" },
  { term = "pubic", type = "exact", action = "block_and_mute" },
  { term = "pubis", type = "exact", action = "block_and_mute" },
  { term = "punkass", type = "exact", action = "block_and_mute" },
  { term = "punky", type = "exact", action = "block_and_mute" },
  { term = "puss", type = "exact", action = "block_and_mute" },
  { term = "pusse", type = "exact", action = "block_and_mute" },
  { term = "pussi", type = "exact", action = "block_and_mute" },
  { term = "pussies", type = "exact", action = "block_and_mute" },
  { term = "pussy", type = "exact", action = "block_and_mute" },
  { term = "pussyfart", type = "exact", action = "block_and_mute" },
  { term = "pussypalace", type = "exact", action = "block_and_mute" },
  { term = "pussypounder", type = "exact", action = "block_and_mute" },
  { term = "pussys", type = "exact", action = "block_and_mute" },
  { term = "puto", type = "exact", action = "block_and_mute" },
  { term = "queaf", type = "exact", action = "block_and_mute" },
  { term = "queef", type = "exact", action = "block_and_mute" },
  { term = "queer", type = "exact", action = "block_and_mute" },
  { term = "queero", type = "exact", action = "block_and_mute" },
  { term = "queers", type = "exact", action = "block_and_mute" },
  { term = "quicky", type = "exact", action = "block_and_mute" },
  { term = "quim", type = "exact", action = "block_and_mute" },
  { term = "racy", type = "exact", action = "block_and_mute" },
  { term = "rape", type = "exact", action = "block_and_mute" },
  { term = "raped", type = "exact", action = "block_and_mute" },
  { term = "raper", type = "exact", action = "block_and_mute" },
  { term = "raping", type = "exact", action = "block_and_mute" },
  { term = "rapist", type = "exact", action = "block_and_mute" },
  { term = "raunch", type = "exact", action = "block_and_mute" },
  { term = "rectal", type = "exact", action = "block_and_mute" },
  { term = "rectum", type = "exact", action = "block_and_mute" },
  { term = "rectus", type = "exact", action = "block_and_mute" },
  { term = "reefer", type = "exact", action = "block_and_mute" },
  { term = "reetard", type = "exact", action = "block_and_mute" },
  { term = "reich", type = "exact", action = "block_and_mute" },
  { term = "retarded", type = "exact", action = "block_and_mute" },
  { term = "revue", type = "exact", action = "block_and_mute" },
  { term = "rimjaw", type = "exact", action = "block_and_mute" },
  { term = "rimjob", type = "exact", action = "block_and_mute" },
  { term = "rimming", type = "exact", action = "block_and_mute" },
  { term = "ritard", type = "exact", action = "block_and_mute" },
  { term = "rtard", type = "exact", action = "block_and_mute" },
  { term = "rum", type = "exact", action = "block_and_mute" },
  { term = "rump", type = "exact", action = "block_and_mute" },
  { term = "rumprammer", type = "exact", action = "block_and_mute" },
  { term = "ruski", type = "exact", action = "block_and_mute" },
  { term = "sadism", type = "exact", action = "block_and_mute" },
  { term = "sadist", type = "exact", action = "block_and_mute" },
  { term = "sandbar", type = "exact", action = "block_and_mute" },
  { term = "sausagequeen", type = "exact", action = "block_and_mute" },
  { term = "scag", type = "exact", action = "block_and_mute" },
  { term = "scantily", type = "exact", action = "block_and_mute" },
  { term = "schizo", type = "exact", action = "block_and_mute" },
  { term = "schlong", type = "exact", action = "block_and_mute" },
  { term = "scroat", type = "exact", action = "block_and_mute" },
  { term = "scrog", type = "exact", action = "block_and_mute" },
  { term = "scrot", type = "exact", action = "block_and_mute" },
  { term = "scrote", type = "exact", action = "block_and_mute" },
  { term = "scrotum", type = "exact", action = "block_and_mute" },
  { term = "scrud", type = "exact", action = "block_and_mute" },
  { term = "scum", type = "exact", action = "block_and_mute" },
  { term = "seaman", type = "exact", action = "block_and_mute" },
  { term = "seamen", type = "exact", action = "block_and_mute" },
  { term = "seduce", type = "exact", action = "block_and_mute" },
  { term = "semen", type = "exact", action = "block_and_mute" },
  { term = "sex", type = "exact", action = "block_and_mute" },
  { term = "sexual", type = "exact", action = "block_and_mute" },
  { term = "shag", type = "exact", action = "block_and_mute" },
  { term = "shagger", type = "exact", action = "block_and_mute" },
  { term = "shaggin", type = "exact", action = "block_and_mute" },
  { term = "shagging", type = "exact", action = "block_and_mute" },
  { term = "shamedame", type = "exact", action = "block_and_mute" },
  { term = "shemale", type = "exact", action = "block_and_mute" },
  { term = "shibari", type = "exact", action = "block_and_mute" },
  { term = "shibary", type = "exact", action = "block_and_mute" },
  { term = "shit", type = "exact", action = "block_and_mute" },
  { term = "shitdick", type = "exact", action = "block_and_mute" },
  { term = "shite", type = "exact", action = "block_and_mute" },
  { term = "shiteater", type = "exact", action = "block_and_mute" },
  { term = "shited", type = "exact", action = "block_and_mute" },
  { term = "shitey", type = "exact", action = "block_and_mute" },
  { term = "shitface", type = "exact", action = "block_and_mute" },
  { term = "shitfuck", type = "exact", action = "block_and_mute" },
  { term = "shitfucker", type = "exact", action = "block_and_mute" },
  { term = "shitfull", type = "exact", action = "block_and_mute" },
  { term = "shithead", type = "exact", action = "block_and_mute" },
  { term = "shithole", type = "exact", action = "block_and_mute" },
  { term = "shithouse", type = "exact", action = "block_and_mute" },
  { term = "shiting", type = "exact", action = "block_and_mute" },
  { term = "shitings", type = "exact", action = "block_and_mute" },
  { term = "shits", type = "exact", action = "block_and_mute" },
  { term = "shitt", type = "exact", action = "block_and_mute" },
  { term = "shitted", type = "exact", action = "block_and_mute" },
  { term = "shitter", type = "exact", action = "block_and_mute" },
  { term = "shitters", type = "exact", action = "block_and_mute" },
  { term = "shitting", type = "exact", action = "block_and_mute" },
  { term = "shittings", type = "exact", action = "block_and_mute" },
  { term = "shitty", type = "exact", action = "block_and_mute" },
  { term = "shiz", type = "exact", action = "block_and_mute" },
  { term = "shota", type = "exact", action = "block_and_mute" },
  { term = "sissy", type = "exact", action = "block_and_mute" },
  { term = "skag", type = "exact", action = "block_and_mute" },
  { term = "skank", type = "exact", action = "block_and_mute" },
  { term = "slave", type = "exact", action = "block_and_mute" },
  { term = "sleaze", type = "exact", action = "block_and_mute" },
  { term = "sleazy", type = "exact", action = "block_and_mute" },
  { term = "slope", type = "exact", action = "block_and_mute" },
  { term = "slut", type = "exact", action = "block_and_mute" },
  { term = "slutbucket", type = "exact", action = "block_and_mute" },
  { term = "slutdumper", type = "exact", action = "block_and_mute" },
  { term = "slutkiss", type = "exact", action = "block_and_mute" },
  { term = "sluts", type = "exact", action = "block_and_mute" },
  { term = "smegma", type = "exact", action = "block_and_mute" },
  { term = "smut", type = "exact", action = "block_and_mute" },
  { term = "smutty", type = "exact", action = "block_and_mute" },
  { term = "snatch", type = "exact", action = "block_and_mute" },
  { term = "sniper", type = "exact", action = "block_and_mute" },
  { term = "snuff", type = "exact", action = "block_and_mute" },
  { term = "sodom", type = "exact", action = "block_and_mute" },
  { term = "son-of-a-bitch", type = "exact", action = "block_and_mute" },
  { term = "souse", type = "exact", action = "block_and_mute" },
  { term = "soused", type = "exact", action = "block_and_mute" },
  { term = "spac", type = "exact", action = "block_and_mute" },
  { term = "sperm", type = "exact", action = "block_and_mute" },
  { term = "spic", type = "exact", action = "block_and_mute" },
  { term = "spick", type = "exact", action = "block_and_mute" },
  { term = "spik", type = "exact", action = "block_and_mute" },
  { term = "spiks", type = "exact", action = "block_and_mute" },
  { term = "spooge", type = "exact", action = "block_and_mute" },
  { term = "spunk", type = "exact", action = "block_and_mute" },
  { term = "steamy", type = "exact", action = "block_and_mute" },
  { term = "stfu", type = "exact", action = "block_and_mute" },
  { term = "stiffy", type = "exact", action = "block_and_mute" },
  { term = "stoned", type = "exact", action = "block_and_mute" },
  { term = "strip", type = "exact", action = "block_and_mute" },
  { term = "strip club", type = "exact", action = "block_and_mute" },
  { term = "stripclub", type = "exact", action = "block_and_mute" },
  { term = "stroke", type = "exact", action = "block_and_mute" },
  { term = "suck", type = "exact", action = "block_and_mute" },
  { term = "sucked", type = "exact", action = "block_and_mute" },
  { term = "sucking", type = "exact", action = "block_and_mute" },
  { term = "sumofabiatch", type = "exact", action = "block_and_mute" },
  { term = "tampon", type = "exact", action = "block_and_mute" },
  { term = "tard", type = "exact", action = "block_and_mute" },
  { term = "tawdry", type = "exact", action = "block_and_mute" },
  { term = "teabagging", type = "exact", action = "block_and_mute" },
  { term = "teat", type = "exact", action = "block_and_mute" },
  { term = "teets", type = "exact", action = "block_and_mute" },
  { term = "teez", type = "exact", action = "block_and_mute" },
  { term = "terd", type = "exact", action = "block_and_mute" },
  { term = "teste", type = "exact", action = "block_and_mute" },
  { term = "testee", type = "exact", action = "block_and_mute" },
  { term = "testes", type = "exact", action = "block_and_mute" },
  { term = "testical", type = "exact", action = "block_and_mute" },
  { term = "testicle", type = "exact", action = "block_and_mute" },
  { term = "testis", type = "exact", action = "block_and_mute" },
  { term = "threesome", type = "exact", action = "block_and_mute" },
  { term = "throating", type = "exact", action = "block_and_mute" },
  { term = "thrust", type = "exact", action = "block_and_mute" },
  { term = "thug", type = "exact", action = "block_and_mute" },
  { term = "tinkle", type = "exact", action = "block_and_mute" },
  { term = "tit", type = "exact", action = "block_and_mute" },
  { term = "titfuck", type = "exact", action = "block_and_mute" },
  { term = "titi", type = "exact", action = "block_and_mute" },
  { term = "tits", type = "exact", action = "block_and_mute" },
  { term = "titt", type = "exact", action = "block_and_mute" },
  { term = "tittiefucker", type = "exact", action = "block_and_mute" },
  { term = "titties", type = "exact", action = "block_and_mute" },
  { term = "titty", type = "exact", action = "block_and_mute" },
  { term = "tittyfuck", type = "exact", action = "block_and_mute" },
  { term = "tittyfucker", type = "exact", action = "block_and_mute" },
  { term = "tittywank", type = "exact", action = "block_and_mute" },
  { term = "titwank", type = "exact", action = "block_and_mute" },
  { term = "toke", type = "exact", action = "block_and_mute" },
  { term = "toots", type = "exact", action = "block_and_mute" },
  { term = "tosser", type = "exact", action = "block_and_mute" },
  { term = "tramp", type = "exact", action = "block_and_mute" },
  { term = "transsexual", type = "exact", action = "block_and_mute" },
  { term = "trashy", type = "exact", action = "block_and_mute" },
  { term = "tubgirl", type = "exact", action = "block_and_mute" },
  { term = "turd", type = "exact", action = "block_and_mute" },
  { term = "tush", type = "exact", action = "block_and_mute" },
  { term = "twat", type = "exact", action = "block_and_mute" },
  { term = "twathead", type = "exact", action = "block_and_mute" },
  { term = "twats", type = "exact", action = "block_and_mute" },
  { term = "twatty", type = "exact", action = "block_and_mute" },
  { term = "twunt", type = "exact", action = "block_and_mute" },
  { term = "twunter", type = "exact", action = "block_and_mute" },
  { term = "undies", type = "exact", action = "block_and_mute" },
  { term = "unwed", type = "exact", action = "block_and_mute" },
  { term = "urinal", type = "exact", action = "block_and_mute" },
  { term = "urine", type = "exact", action = "block_and_mute" },
  { term = "uterus", type = "exact", action = "block_and_mute" },
  { term = "vag", type = "exact", action = "block_and_mute" },
  { term = "vagina", type = "exact", action = "block_and_mute" },
  { term = "valium", type = "exact", action = "block_and_mute" },
  { term = "viagra", type = "exact", action = "block_and_mute" },
  { term = "vigra", type = "exact", action = "block_and_mute" },
  { term = "virgin", type = "exact", action = "replace", replacement = "person" },
  { term = "vixen", type = "exact", action = "block_and_mute" },
  { term = "vodka", type = "exact", action = "block_and_mute" },
  { term = "vomit", type = "exact", action = "block_and_mute" },
  { term = "voyeur", type = "exact", action = "block_and_mute" },
  { term = "vulgar", type = "exact", action = "block_and_mute" },
  { term = "vulva", type = "exact", action = "block_and_mute" },
  { term = "wad", type = "exact", action = "block_and_mute" },
  { term = "wang", type = "exact", action = "block_and_mute" },
  { term = "wank", type = "exact", action = "block_and_mute" },
  { term = "wanker", type = "exact", action = "block_and_mute" },
  { term = "wanky", type = "exact", action = "block_and_mute" },
  { term = "wazoo", type = "exact", action = "block_and_mute" },
  { term = "wedgie", type = "exact", action = "block_and_mute" },
  { term = "weed", type = "exact", action = "block_and_mute" },
  { term = "weenie", type = "exact", action = "block_and_mute" },
  { term = "weewee", type = "exact", action = "block_and_mute" },
  { term = "weiner", type = "exact", action = "block_and_mute" },
  { term = "wench", type = "exact", action = "block_and_mute" },
  { term = "wetback", type = "exact", action = "block_and_mute" },
  { term = "whitey", type = "exact", action = "block_and_mute" },
  { term = "whiz", type = "exact", action = "block_and_mute" },
  { term = "whoar", type = "exact", action = "block_and_mute" },
  { term = "whoralicious", type = "exact", action = "block_and_mute" },
  { term = "whore", type = "exact", action = "block_and_mute" },
  { term = "whorealicious", type = "exact", action = "block_and_mute" },
  { term = "whored", type = "exact", action = "block_and_mute" },
  { term = "whoreface", type = "exact", action = "block_and_mute" },
  { term = "whorehopper", type = "exact", action = "block_and_mute" },
  { term = "whorehouse", type = "exact", action = "block_and_mute" },
  { term = "whores", type = "exact", action = "block_and_mute" },
  { term = "whoring", type = "exact", action = "block_and_mute" },
  { term = "wigger", type = "exact", action = "block_and_mute" },
  { term = "willies", type = "exact", action = "block_and_mute" },
  { term = "willy", type = "exact", action = "block_and_mute" },
  { term = "womb", type = "exact", action = "block_and_mute" },
  { term = "woody", type = "exact", action = "block_and_mute" },
  { term = "woose", type = "exact", action = "block_and_mute" },
  { term = "wop", type = "exact", action = "block_and_mute" },
  { term = "x-rated2g1c", type = "exact", action = "block_and_mute" },
  { term = "xx", type = "exact", action = "block_and_mute" },
  { term = "xxx", type = "exact", action = "block_and_mute" },
  { term = "yaoi", type = "exact", action = "block_and_mute" },
  { term = "yury", type = "exact", action = "block_and_mute" },
  { term = "holocaust", type = "exact", action = "block_and_mute" },
  { term = "kys", type = "exact", action = "block_and_mute" },
  { term = "kill yourself", type = "exact", action = "block_and_mute" },
  { term = "suicide", type = "exact", action = "block_and_mute" },
  { term = "hang yourself", type = "exact", action = "block_and_mute" },
  { term = "tranny", type = "wildcard", action = "block_and_mute" },
  { term = "trap", type = "exact", action = "block_and_mute" },
  { term = "simp", type = "exact", action = "block_and_mute" },
  { term = "incel", type = "exact", action = "block_and_mute" },
  { term = "beaner", type = "exact", action = "block_and_mute" },
  { term = "raghead", type = "exact", action = "block_and_mute" },
  { term = "towlehead", type = "exact", action = "block_and_mute" },
  { term = "camel jockey", type = "exact", action = "block_and_mute" },
  { term = "porch monkey", type = "exact", action = "block_and_mute" },
  { term = "tar baby", type = "exact", action = "block_and_mute" },
  { term = "jigaboo", type = "exact", action = "block_and_mute" },
  { term = "golliwog", type = "exact", action = "block_and_mute" },
  { term = "isis", type = "exact", action = "block_and_mute" },
  { term = "al qaeda", type = "exact", action = "block_and_mute" },
  { term = "nazis", type = "exact", action = "block_and_mute" },
  { term = "white power", type = "exact", action = "block_and_mute" },
  { term = "mongoloid", type = "exact", action = "block_and_mute" },
  { term = "obese", type = "exact", action = "replace", replacement = "large" },
  { term = "blackface", type = "exact", action = "block_and_mute" },
  { term = "swatting", type = "exact", action = "block_and_mute" },
  { term = "doxxing", type = "exact", action = "block_and_mute" },
}

local function escape_pattern(text)
  return text:gsub("([^%w])", "%%%1")
end

local function case_insensitive_pattern(text)
  local pat = ""
  for i = 1, #text do
    local c = text:sub(i, i)
    if c:match("%a") then
      pat = pat .. "[" .. c:lower() .. c:upper() .. "]"
    else
      pat = pat .. escape_pattern(c)
    end
  end
  return pat
end

local function normalize_leetspeak(text)
  local t = text:lower()
  t = t:gsub("1", "i")
  t = t:gsub("!", "i")
  t = t:gsub("3", "e")
  t = t:gsub("4", "a")
  t = t:gsub("@", "a")
  t = t:gsub("5", "s")
  t = t:gsub("7", "t")
  t = t:gsub("0", "o")
  t = t:gsub("%$", "s")
  t = t:gsub("[%p%s]", "")
  return t
end

local _compiled_patterns = nil

local function compile_patterns()
  if _compiled_patterns then return _compiled_patterns end
  _compiled_patterns = {}
  for i = 1, #FILTERED_TERMS do
    local entry = FILTERED_TERMS[i]
    local term = entry.term or ""
    local replace_with = entry.replacement or "***"
    local pat
    local norm_term
    if entry.type == "wildcard" then
      local prefix = term:gsub("%*$", "")
      pat = "%f[%a]" .. case_insensitive_pattern(prefix) .. "%w*"
      norm_term = normalize_leetspeak(prefix)
    else
      local is_single_word = term:match("^%a+$")
      if is_single_word then
        pat = "%f[%a]" .. case_insensitive_pattern(term) .. "%f[%A]"
      else
        pat = case_insensitive_pattern(term)
      end
      norm_term = normalize_leetspeak(term)
    end
    _compiled_patterns[i] = {
      pat = pat,
      replace_with = replace_with,
      norm_term = norm_term,
    }
  end
  return _compiled_patterns
end

function Filtered.sanitize(text)
  if type(text) ~= "string" or text == "" then
    return text or ""
  end
  local patterns = compile_patterns()
  local out = text
  local normalized = normalize_leetspeak(text)
  local matched_normalized = false
  local replaced_any = false
  for i = 1, #patterns do
    local cp = patterns[i]
    local new_out, count = out:gsub(cp.pat, cp.replace_with)
    if count > 0 then
      out = new_out
      replaced_any = true
    end
    if not matched_normalized and normalized:find(cp.norm_term, 1, true) then
      matched_normalized = true
    end
  end
  if matched_normalized and not replaced_any then
    out = "***"
  end
  return out
end

return Filtered
